import type { components } from './generated/api'
export type ProjectInput = components['schemas']['ProjectIn']
export type ExperimentInput = components['schemas']['ExperimentIn']
export type ContractInput = components['schemas']['ContractIn']
export interface Rate { numerator: number; denominator: number; rate: number | null; interval: [number, number] | null }
export interface Comparison { earlier: Rate; later: Rate; change: { pp: number | null; interval: [number, number] | null } }
export interface Row { period: 'earlier' | 'later'; cohort_start: string; cohort_end: string; segment: string; signups: number; activated: number; retained: number; retained_activated: number; a7_mature?: boolean; w4_mature?: boolean; activation?: Rate; retention?: Rate }
export type Metric = 'retention' | 'activation' | 'conditional'
export interface Analysis { metrics: Record<Metric, Comparison>; segments: (Comparison & { segment: string })[]; cohorts: Row[]; excluded: {cohort_start: string; cohort_end: string; segment: string; eligible_on: string; signups: number}[]; standardized_later: number | null; mature_cohorts: number; periods: Record<string, {start: string; end: string}> }
export interface Brief { intervention_evidence?:{id:string;title:string;outcome:Experiment['outcome']}[]; pivot_eligibility?:{eligible:boolean;missing:string[]}; research_evidence?:{id:string;name:string;type:string;recruitment_source:string;response_count:number}[]; state: string; title: string; summary: string; analysis: Analysis; evidence: (Comparison & {id: string; type: string; label: string; snapshot_id: string})[]; contradictions: string[]; missing: string[]; limitations: string[]; what_would_change: string; next_experiment: string; dimensions: Record<string, string>; rule_version: string; synthetic: boolean }
export interface Assessment { contract_id?: string; id: string; version: number; created_at: string; owner_name: string; review_date: string; analyst_note: string; brief: Brief; snapshot_id: string }
export interface Project extends Required<ProjectInput> { id: string; name: string; promise: string; audience: string; concern: string; cadence: 'weekly'; is_demo: boolean; raw_retention_days: number; aggregate_retention_days: number; run_budget_limit: string; workspace_id: string }
export interface Contract { id: string; version: number; content_hash: string; config: { entry_event: string; value_event: string; return_event: string; segment_properties: string[]; minimum_detectable_change_pp: number | null; viability_target: number | null; baseline_approved: boolean; review_windows?: {start:string;end:string}[]; [key: string]: unknown } }
export interface HumanSummary { n: number; mean: number; counts: number[]; distribution: number[] }
export interface Study { id: string; title: string; audience: string; question: string; hypothesis: string; version: number; concepts: {id: string; name: string; description: string; group: string; split: string; version: number}[]; human_summary: Record<string, HumanSummary>; datasets: {id: string; name: string; summary: Record<string, HumanSummary>; response_count: number; expired: boolean; expires_at: string; metadata: {synthetic: boolean; recruitment_source: string}}[]; runs: {id: string; budget: number; spent: number; uncertain_cost: number; reserved: number; summary: Record<string, unknown>; config: Record<string, unknown>; job: Job}[] }
export interface Experiment { id: string; title: string; hypothesis: string; population: string; assignment_unit: string; design: string; primary_metric: string; minimum_effect: string; guardrails: string; stopping_rule: string; instrumentation_check: string; owner_name: string; review_date: string; status: 'planned' | 'running' | 'complete'; outcome: {decision: string; result: string; evidence: string; limitations: string} | null }
export interface Job { id: string; kind: string; status: string; progress: number; error: string }
export interface Connection { id: string; region: string; external_project_id: number; endpoints: Record<string, unknown>; status: string; last_error: string; last_refresh: string | null }
export interface Overview { snapshot_versions: {id:string; collected_at:string; analysis_cutoff:string; source:string; contract_id:string}[]; project: Project; role: string; can_export: boolean; assessment: Assessment | null; assessment_versions: {id: string; version: number; created_at: string}[]; contract: Contract | null; connection: Connection | null; studies: Study[]; experiments: Experiment[]; jobs: Job[] }
export interface Source { id: string; source: string; rows: Row[]; quality: Record<string, boolean | string | string[]>; source_metadata: Record<string, unknown>; content_hash: string; analysis_cutoff: string; latest_event_at: string | null; collected_at: string; contract: Contract; exclusions: string; counting_unit: string }
export interface Session { authenticated: boolean; username: string; csrf_token: string; demo_enabled: boolean; registration_enabled: boolean; model_enabled: boolean }
