# Generated by Django 5.2.17 on 2026-09-07 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=20)),
                ('rows', models.JSONField()),
                ('quality', models.JSONField(default=dict)),
                ('source_metadata', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('analysis_cutoff', models.DateTimeField()),
                ('latest_event_at', models.DateTimeField(null=True)),
                ('collected_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=160)),
                ('promise', models.TextField(blank=True)),
                ('audience', models.TextField(blank=True)),
                ('concern', models.TextField(blank=True)),
                ('cadence', models.CharField(default='weekly', max_length=30)),
                ('is_demo', models.BooleanField(default=False)),
                ('raw_retention_days', models.PositiveIntegerField(default=30)),
                ('aggregate_retention_days', models.PositiveIntegerField(default=90)),
                ('run_budget_limit', models.DecimalField(decimal_places=2, default=5, max_digits=8)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=160)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField()),
                ('brief', models.JSONField()),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('review_date', models.DateField(null=True)),
                ('analyst_note', models.TextField(blank=True)),
                ('snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.analyticssnapshot')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='queued', max_length=24)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('lease_until', models.DateTimeField(null=True)),
                ('lease_token', models.UUIDField(null=True)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('result', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='MetricContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField()),
                ('config', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.project')),
            ],
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.metriccontract'),
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=180)),
                ('hypothesis', models.TextField()),
                ('population', models.TextField()),
                ('assignment_unit', models.CharField(default='identified_user', max_length=80)),
                ('design', models.CharField(default='randomized', max_length=30)),
                ('primary_metric', models.CharField(max_length=180)),
                ('minimum_effect', models.CharField(blank=True, max_length=100)),
                ('guardrails', models.TextField()),
                ('stopping_rule', models.TextField()),
                ('instrumentation_check', models.TextField(blank=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('review_date', models.DateField()),
                ('status', models.CharField(default='planned', max_length=20)),
                ('outcome', models.JSONField(null=True)),
                ('assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.assessment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(max_length=2)),
                ('external_project_id', models.PositiveIntegerField()),
                ('credential', models.TextField()),
                ('endpoints', models.JSONField(default=dict)),
                ('contract_hash', models.CharField(max_length=64)),
                ('status', models.CharField(default='connected', max_length=20)),
                ('last_error', models.CharField(blank=True, max_length=400)),
                ('last_refresh', models.DateTimeField(null=True)),
                ('daily_refresh', models.BooleanField(default=False)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.CharField(max_length=60)),
                ('resource_id', models.CharField(max_length=80)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.project'),
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=160)),
                ('audience', models.TextField()),
                ('question', models.TextField()),
                ('hypothesis', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PanelRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.JSONField()),
                ('budget', models.DecimalField(decimal_places=4, max_digits=8)),
                ('spent', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('reserved', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('uncertain_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('summary', models.JSONField(default=dict)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panel_run', to='core.job')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HumanDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=180)),
                ('rows', models.JSONField(default=list)),
                ('summary', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('expired', models.BooleanField(default=False)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='core.study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('group', models.CharField(max_length=120)),
                ('split', models.CharField(default='development', max_length=20)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='core.study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.workspace'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], max_length=10)),
                ('can_export', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='PanelResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persona', models.PositiveIntegerField()),
                ('draw', models.PositiveIntegerField(default=0)),
                ('method', models.CharField(max_length=30)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('usage', models.JSONField(default=dict)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.concept')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.panelrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'concept', 'persona', 'draw', 'method'), name='unique_panel_response')],
            },
        ),
        migrations.AddConstraint(
            model_name='metriccontract',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='unique_contract_version'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'lease_until'], name='core_job_status_eac7f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('project', 'kind', 'idempotency_key'), name='unique_job_request'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='unique_assessment_version'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='unique_membership'),
        ),
    ]
